# The default image to use when user image is missing.
default-image: https://upload.wikimedia.org/wikipedia/commons/c/cd/Portrait_Placeholder_Square.png

collections:
  profile:
    output: true

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

jekyll-mentions:
    base_url: https://github.com
